### ISSUE TITLE
downgrading numpy and scipy requirements

### ISSUE THREAD

**Issue by gngdb** [edinburghlivinglab/dds-notebooks#12]
I'm building the python stack for our JupyterHub instance off the [ipython scipystack](https://github.com/ipython/docker-notebook/tree/master/scipystack) because it has a nice reliable installation of OpenBLAS with numpy and scipy ready. Compiling numpy and scipy can take a while, so it seems like going from this is a nice way to break up the image build. But, our numpy and scipy requirements are ahead of theirs. I doubt we're going to have any problems going back to scipy 0.14.0 and numpy 1.9.0, right? 

In the mean time, I'll just install the most recent versions, but we'll lose OpenBLAS support, which might have consequences.

**Comment by fvargas-icerobotics** [comment]
I really dont think the downgrade will be a problem. It should be fine.
