### ISSUE TITLE
Files created when rendering html Map in notebook (4 files in total)

### ISSUE THREAD

**Issue by franciscovargas** [edinburghlivinglab/dds-notebooks#15]
Whenever folium is used to render a map html, json,js files are created in the source directory of the notebook the rendering is done by. I cant seem to manage to carry out a procedure which allows the rendering to happen and automarically deletes the files post the rendering within the same ipython-notebook code snippet. So I am not sure how to deal with this.  @gngdb  Would it be possible to have a routine that takes place each time a specific notebook is closed ?

**Comment by franciscovargas** [comment]
never mind found an easy fix with folium....

**Comment by franciscovargas** [comment]
I have managed a partial fix by creating a folder called metadata within the notebooks folder and this is where all the html files needed to render the choropleth go. I think it is a good idea ?

**Comment by ewan-klein** [comment]
This sounds like a good approach. But I wonder whether we should choose a different name from 'metadata'. Maybe 'build-data'?

**Comment by franciscovargas** [comment]
yeah I dont know why I called it metadata... folder names are not my forte.
It is also possible for this folder to actually be inside the data folder
and not the ipython one within data a folder called ipython_build_data for
example but I dont know if this is any better.
