### ISSUE TITLE
Error in ScatterPlots.ipynb

### ISSUE THREAD

**Issue by gngdb** [edinburghlivinglab/dds-notebooks#18]
Trying to run this notebook on the new server getting the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-2cc38e449858> in <module>()
      5 
      6 # Plot scatter plot matrix:
----> 7 g = c.plot_pairs()

/opt/dds-notebooks/dds_lab/climdat.py in plot_pairs(self)
    254                                      fill_color='red', size=13, source=cds_dict[k + '1'])
    255             s1.select(dict(type=HoverTool)).tooltips = {
--> 256                 "x": "$x", "y": "$y", "year": "@desc"}
    257             s2 = fig_dict[k].scatter(np.array(v[2])[:, 1], np.array(v[3])[:, 1],
    258                                      fill_color='green', size=10, source=cds_dict[k + '2'])

AttributeError: 'generator' object has no attribute 'tooltips'
```

Sign onto the new server with your EASE credentials to reproduce.

**Comment by franciscovargas** [comment]
How can I get access to the server ?

**Comment by franciscovargas** [comment]
sounds like an either old or new version oh bokeh bug.  For some reason whenever I run jupyterhub from a  keysurf connection I always get a  "The page isn't redirecting properly" bug when trying to access the notebook server.

**Comment by gngdb** [comment]
Server is running here: https://jupyter-inf.is.ed.ac.uk/

Should be accesible from anywhere.

**Comment by franciscovargas** [comment]
what version of our jupyterhub fork is this running ?

**Comment by franciscovargas** [comment]
(I cant check what the collors for the sign in box look like for example since its already signed in, the most updated version has them in blue as opposed to orange).

**Comment by gngdb** [comment]
Looks like it's installed at this commit:

```
commit e1f7b3361a229cacae0ef6018406b6a7ef9c036c
Author: franciscovargas <vargfran@gmail.com>
Date:   Sat Dec 19 21:06:20 2015 +0000

    fixed redirection issue
```

**Comment by franciscovargas** [comment]
thanks let me look in to it !

**Comment by franciscovargas** [comment]
Thats perfect ! thats the most updated commit so I can tidy up the HTML page it lands on.  Whats the best way to go about testing with this and fixing the bokeh bug ?

**Comment by franciscovargas** [comment]
fixed. Worth getting the server to pull the new commit and testing again.  (I tested it within the server)
