### ISSUE TITLE
query about requirements.txt

### ISSUE THREAD

**Issue by ewan-klein** [edinburghlivinglab/dds-notebooks#6]
The versions in `requirements.txt` are all specified via `==`. However, for some of the dependencies, I already have newer versions installed on my machine. Any reason not to use `>=` in place of `==`?

**Comment by franciscovargas** [comment]
No I see no reason why not to, even for doccumentation purposes `>=` should do in terms of reminding that these were the original configs . At some point I will go over the dependancies and clean out things that may not be needed.
