### ISSUE TITLE
restructuring of examples/notebooks[Janitorial work]

### ISSUE THREAD

**Issue by franciscovargas** [edinburghlivinglab/dds-notebooks#7]
Restructutre the project directory.

**Comment by ewan-klein** [comment]
@franciscovargas Can we have two directories for notebooks? One for experimental / playing around stuff and a second one which are drafts of notebooks intended for the students?

Eg we replace

```
examples
        notebooks
```

by something like

```
notebooks
scratch-notebooks
```

**Comment by fvargas-icerobotics** [comment]
Yes that seems great ! we discussed this in the meeting. I was thinking
what to restructure it in to but had not come to any final decisions. This
seems perfect.

**Comment by ewan-klein** [comment]
OK. I'll leave it to you. :smile:
